services:
  db:
    image: postgres:16
    container_name: practise2-postgres
    environment:
      POSTGRES_DB: practise2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: