create table customers(
    id BIGINT GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
    name varchar(20) NOT NULL
);

create table customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    description varchar(200) NOT NULL
);

create table order_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message varchar(200) NOT NULL
);

